module.exports=(sequelize,DataTypes)=>{
    const Employees=sequelize.define("employees",{
        employeeNumber:{
            type:DataTypes.NUMBER,
            allowNull:false
        },
        lastName:{
            type:DataTypes.STRING,
            allowNull:false
        },
        firstName:{
            type:DataTypes.STRING,
            allowNull:false
        },
        extension:{
            type:DataTypes.STRING,
            allowNull:false
        },
        email:{
            type:DataTypes.STRING,
            allowNull:false
        },
        officeCode:{
            type:DataTypes.STRING,
            allowNull:false
        },
        reportsTo:{
            type:DataTypes.NUMBER,
        },
        jobTitle:{
            type:DataTypes.STRING,
            allowNull:false
        }
    });
    return Employees;
}