module.exports=(sequelize,DataTypes)=>{
    const Products=sequelize.define("products",{
        productCode:{
            type:DataTypes.STRING,
            allowNull:false
        },
        productName:{
            type:DataTypes.STRING,
            allowNull:false
        },
        productLine:{
            type:DataTypes.STRING,
            allowNull:false
        },
        productScale:{
            type:DataTypes.STRING,
            allowNull:false
        },
        productVendor:{
            type:DataTypes.STRING,
            allowNull:false
        },
        productDescription:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        quantityInStock:{
            type:DataTypes.NUMBER,
            allowNull:false
        },
        buyPrice:{
            type:DataTypes.FLOAT,
            allowNull:false
        },
        MSRP:{
            type:DataTypes.FLOAT,
            allowNull:false
        }
    });
    return Products;
}